// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-Rf0Kfz6UjYagwU58XT-vgg1MDLlUOw',
    appId: '1:561774745761:web:9f3a3166ce9c2f1bafb8e0',
    messagingSenderId: '561774745761',
    projectId: 'neuroukey',
    authDomain: 'neuroukey.firebaseapp.com',
    storageBucket: 'neuroukey.appspot.com',
    measurementId: 'G-8FX96ZZDPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB937a5QYZ_FP6jW-c-txdda6eRTYM7G_g',
    appId: '1:561774745761:android:1f55c24a5aba7c8fafb8e0',
    messagingSenderId: '561774745761',
    projectId: 'neuroukey',
    storageBucket: 'neuroukey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQM1ciSpNx51KWwADEI-PF1z_pVHVtE8',
    appId: '1:561774745761:ios:e43b7756edb93596afb8e0',
    messagingSenderId: '561774745761',
    projectId: 'neuroukey',
    storageBucket: 'neuroukey.appspot.com',
    iosBundleId: 'com.munkey.neuroukey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQM1ciSpNx51KWwADEI-PF1z_pVHVtE8',
    appId: '1:561774745761:ios:e43b7756edb93596afb8e0',
    messagingSenderId: '561774745761',
    projectId: 'neuroukey',
    storageBucket: 'neuroukey.appspot.com',
    iosBundleId: 'com.munkey.neuroukey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL-Rf0Kfz6UjYagwU58XT-vgg1MDLlUOw',
    appId: '1:561774745761:web:bbcb1f9ddc9fad48afb8e0',
    messagingSenderId: '561774745761',
    projectId: 'neuroukey',
    authDomain: 'neuroukey.firebaseapp.com',
    storageBucket: 'neuroukey.appspot.com',
    measurementId: 'G-07ZN46313W',
  );
}
